flex1:
	flex 1.l
	gcc lex.yy.c
	./a.exe < input1.txt > output.txt

flex2:
	flex 2.l
	gcc lex.yy.c
	./a.exe < input2.txt > output.txt

flex3:
	flex 3.l
	gcc lex.yy.c
	./a.exe < input3.txt > output.txt

flex4:
	flex 4.l
	gcc lex.yy.c
	./a.exe < input4.txt > output.txt

