bison1:
	bison -d 1b.y
	flex 1b.l
	gcc lex.yy.c 1b.tab.c
	./a.exe < input1.txt

bison2:
	bison -d 2b.y
	flex 2b.l
	gcc lex.yy.c 2b.tab.c
	./a.exe < input2.txt

bison3:
	bison -d 3b.y
	flex 3b.l
	gcc lex.yy.c 3b.tab.c
	./a.exe < input3.txt
bison4:
	bison -d 4b.y
	flex 4b.l
	gcc lex.yy.c 4b.tab.c
	./a.exe < input4.txt