prog1:
	bison -d prog1.y
	flex prog1.l
	gcc prog1.tab.c lex.yy.c
	a.exe <input.txt> output.txt
prog2:
	flex prog2.l
	gcc lex.yy.c
	a <input.txt> output.txt

prog3:
	flex prog3.l
	gcc lex.yy.c
	a <input.txt> output.txt
prog4:
	flex prog4.l
	gcc lex.yy.c
	a <input.txt> output.txt
prog5:
	flex prog5.l
	gcc lex.yy.c
	a <input.txt> output.txt